#!/bin/bash

REPO=fopina/docker-octoprint

set -e

if [ -z "$1" ]; then
    echo "missing token"
    exit 2
fi

pip install pip-upgrader
pip-upgrade --skip-package-installation -p octoprint

if [ -z "git diff" ]; then
    echo "No updates were found"
    exit 0
fi

NEW_VERSION=$(cat requirements.txt| cut -d '=' -f3)

echo "Update detected: ${NEW_VERSION}"

git config user.email updater@devnull.localhost
git config user.name Updater

BRANCH=dependency-update/xoctoprint-${NEW_VERSION}

git checkout -b ${BRANCH}

git commit -a -m "bump OctoPrint to ${NEW_VERSION}"

git push origin ${BRANCH}

echo "https://api.github.com/repos/${REPO}/pulls"

response=$(curl -f --write-out "%{message}\n" -X POST -H "Content-Type: application/json" -H "Authorization: token $1" \
        --data '{"title":"Autoupdate dependencies","head": "'"${BRANCH}"'","base":"main", "body":"Auto-generated pull request. \nThis pull request is generated by GitHub action based on the provided update commands."}' \
        "https://api.github.com/repos/${REPO}/pulls")

echo $response

if [[ "$response" == *"already exist"* ]]; then
    echo "Pull request already opened. Updates were pushed to the existing PR instead"
    exit 0
fi
