name: publish to dockerhub

on:
    push:
      branches:
      - master

jobs:
  build:
    name: publish to dockerhub
    runs-on: ubuntu-latest
    env:
      OCTO_VERSION: 1.7.0
      IMAGE_VERSION: 1
    steps:
      - uses: actions/checkout@master

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: login to dockerhub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: build (and publish) main image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg VERSION=${OCTO_VERSION} \
            --push \
            -t fopina/octoprint:${OCTO_VERSION} \
            -t fopina/octoprint:${OCTO_VERSION}.${IMAGE_VERSION} \
            -t fopina/octoprint:latest \
            .
