name: test docker image

on:
  pull_request:

jobs:
  build:
    name: test docker image
    runs-on: ubuntu-latest
    env:
      OCTO_VERSION: 1.7.3
      IMAGE_VERSION: 1
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: build image
        uses: docker/build-push-action@v3
        with:
          tags: fopina/octoprint:test
          load: true
          build-args: |
            VERSION=${OCTO_VERSION}

      - name: test docker image
        run: .github/test.sh fopina/octoprint:test

      # - name: build image
      #   uses: docker/build-push-action@v3
      #   with:
      #     tags: fopina/octoprint:test
      #     outputs: |
      #       x
      #     platforms: |
      #       linux/amd64
      #       inux/arm64
      #       linux/arm/v7
      #     build-args: |
      #       VERSION=${OCTO_VERSION}
